Exam
rulik04/2024-2-VK-EDU-Frontend-R-Alimkhan pull request #8
Opened 2024-12-23 18:14 UTC by rulik04

# Exam

Прошу @martinkomitsky, @haseprogram проверить его.

Что было сделано:

- В корневой папке репозитория создать базовое приложение exam с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) (или vite) по инструкции выше
- Сверстать 2 страницы и необходимые компоненты
- Использовать стили. Дизайн должен быть похожим на макет
- Реализовать перевод с одного языка на другой (нужно сделать так, чтобы можно было выбирать языки из выпадающего списка)
- Реализовать перевод с неизвестного языка (автоопределитель из API)
- Сохранять историю переводов в localStorage
- Использовать React-router для перехода между страницами
- Задеплоить решение, используя GitHub Actions

2024-12-29 19:05 UTC, martinkomitsky commented
Предварительная оценка: 36.
По ревью замечаний нет, но на последний пункт предлагаю выполнить следующее задание:
* Сделать минимальную высоту для textarea
* Убрать Аutodetect из выпадающего списка целевого языка
![image](https://github.com/user-attachments/assets/eb518d0d-2a6b-4083-b718-0569f96f1f8b)

2024-12-29 19:06 UTC, martinkomitsky requested changes
Фиксы сверху

2024-12-31 22:24 UTC, rulik04 reviewed
- Убрал Аutodetect из выпадающего списка целевых языков 
- Сделал минимальную высоту для textarea

C новым годом!

2025-01-01 19:49 UTC, martinkomitsky approved these changes

2025-01-01 19:49 UTC, merged

2025-01-01 19:51 UTC, martinkomitsky commented
> * Убрал Аutodetect из выпадающего списка целевых языков
> * Сделал минимальную высоту для textarea
> 
> C новым годом!

Принял, 46! Ура, с праздником!

Вижу, что у тебя не хватает 42 балла до зачёта. Предлагаю сдать 2 квиза (36 баллов) и одну какую-нибудь самую легкую задачу, как раз будет достаточно. Что скажешь?

2025-01-02 14:13 UTC, rulik04 commented
> Вижу, что у тебя не хватает 42 балла до зачёта. Предлагаю сдать 2 квиза (36 баллов) и одну какую-нибудь самую легкую задачу (например, ДЗ 11 или 12), как раз будет достаточно. Что скажешь?

@martinkomitsky 
Да, если можно, готов сдать.